//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZona.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web;
    using System.Web.Mvc;

    public partial class ABOUTUS
    {
        public int ID { get; set; }

        [Required]
        [Display(Name = "Başlık")]
        public string HEADER { get; set; }


        [AllowHtml]
        [Required]
        [Display(Name = "İçerik")]
        public string SUBJECT { get; set; }
        public byte ACTİVE { get; set; }
        public int ORDER { get; set; }
    }
}
