//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZona.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADMİNLOGİN
    {
        public int ID { get; set; }

        [Required(ErrorMessage = "Lütfen Kullanıcı Adınızı Giriniz!")]
        public string NAMESURNAME { get; set; }

        [Required(ErrorMessage = "Lütfen Şifrenizi Giriniz!")]
        public string PASSWORD { get; set; }
        public Nullable<byte> ROLE { get; set; }

        public virtual bool BeniHatirla { get; set; }
    }
}
