//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZona.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TimeZonaEntities : DbContext
    {
        public TimeZonaEntities()
            : base("name=TimeZonaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ABOUTUS> ABOUTUS { get; set; }
        public virtual DbSet<ADMİNLOGİN> ADMİNLOGİN { get; set; }
        public virtual DbSet<LOGİN> LOGİN { get; set; }
        public virtual DbSet<PRODUCTS> PRODUCTS { get; set; }
        public virtual DbSet<PRODUCTSDETAILS> PRODUCTSDETAILS { get; set; }
        public virtual DbSet<SHOP> SHOP { get; set; }
    }
}
