//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TimeZona.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTS
    {
        public int ID { get; set; }
        public string PHOTO { get; set; }
        public string NAME { get; set; }
        public int PRICE { get; set; }
        public Nullable<int> QUEUE { get; set; }
        public Nullable<byte> ACTİVE { get; set; }
    }
}
